### ISSUE TITLE
Bors says ":-1: Rejected by code reviews" even though the PR was approved

### ISSUE THREAD

**Issue by heinrich5991** [bors-ng/bors-ng#364]
See https://github.com/ddnet/ddnet/pull/1079#issuecomment-372496230. Probably caused by #362.

**Comment by grahamc** [comment]
Ack, I'm sorry! Looks like we've got a PR from notriddle to patch it up. LGTM, should be merged shortly.

**Comment by heinrich5991** [comment]
Thanks, works.

**Comment by vlad20012** [comment]
I've got the same issue at https://github.com/intellij-rust/intellij-rust/pull/2405

**Comment by JensRantil** [comment]
We are seeing the same issue in a private repository:

![op_update_by_mathewclegg_ _pull_request__8562_ _tink-ab_tink-backend23](https://user-images.githubusercontent.com/730342/40412756-76cebd90-5e74-11e8-9f7a-2d971a0c8eaf.png)

![op_update_by_mathewclegg_ _pull_request__8562_ _tink-ab_tink-backend2](https://user-images.githubusercontent.com/730342/40412759-7b1fe194-5e74-11e8-9192-be6d83435a71.png)

Let us know if you need any additional feedback.

**Comment by JensRantil** [comment]
Also, I propose this issue gets reopoened.

**Comment by JensRantil** [comment]
This is still an issue for us and we keep experiencing it a couple of times per day. I've scrolled back a couple of hours back in our webhook history and it doesn't look like we've had any webhook exceptions related to the pull request. So far, I the workaround is to close the pull request and reopen the pull request, have the second person approve it and then `bors r+`. (cc @qinjin)

**Comment by JensRantil** [comment]
I should also mention that this bug also happens if there has only been a single (approval) review. That is, it's not related to multiple "comment reviews" and a single "approve" review.

Let me know if I can give more information to determine what the issue is.

**Comment by notriddle** [comment]
@JensRantil 

Pull request #429 should help with your problem. Can you please update to the newest bors-ng, and let me know if you're still able to reproduce this bug?

**Comment by JensRantil** [comment]
Sweet! 🙏 We haven't had a way to reproduce the bug strictly, but I will share with my team that the bug hopefully is fixed and ask them to get back to me if they experience it again.

**Comment by notriddle** [comment]
I'll close it unless anybody else has run into this problem (#435 should've fixed it).

**Comment by JensRantil** [comment]
@notriddle We are experiencing this with a pull request where I have done a `bors delegate+` to the author. Also, I am unable to initiate a `bors r+` (which I should have access to). Our general feeling is that this generally happen when there are multiple reviewers making multiple reviews with different (request-changes, comment, approved) statuses. Let us know if you'd like us to check something.

cc @krlvl.

**Comment by KaiSzuttor** [comment]
This issue still persists. Why does bors not directly check the mergability via the github api? There should only be a single source of truth.

**Comment by notriddle** [comment]
We specifically want to allow you to configure your repo so that bors is a require status check (that way, you can't accidentally merge directly into master). If you do that, though, then GitHub's "mergable" API will always return `false`.

**Comment by KaiSzuttor** [comment]
that's actually the wrong indicator. the mergable flag of the pull request just indicates whether there are merge conflicts. However, the api can check the sastus of the last commit of the pull request
